version: '3.6'

services:
  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgress://brain:brain@postgres:5432/smart-brain-docker
      # POSTGRES_USER: sally
      # POSTGRES_PASSWORD: secret
      # POSTGRES_DB: smart-brain-docker
      # POSTGRES_HOST: postgres
    # Map docker image port 3000 to our host machine port 3000
    ports:
      - '3000:3000'
    # Allows us to link docker image nodemon backend code changes to our host computer and reload comandline output
    volumes:
      - ./:/usr/src/smart-brain-api
  # Postgres
  postgres:
    environment:
      POSTGRES_USER: brain
      POSTGRES_PASSWORD: brain
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    container_name: postgres
    build: ./postgres
    ports:
      - '5432:5432'
